version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: s2mangas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: s2mangas
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: s2mangas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend

  api:
    build: .
    container_name: s2mangas_api
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/s2mangas"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: production
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
